# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  projects: '**/*.csproj'
  projectToPublish: '**/TuyenPham.Base.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Restore NuGet packages
  inputs:
    command: 'restore'
    projects: '$(projects)'
    configuration: '$(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Build projects
  inputs:
    command: 'build'
    projects: '$(projects)'
    configurationToPack: '$(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Create NuGet package
  inputs:
    command: 'pack'
    configuration: '$(buildConfiguration)'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    packagesToPack: '$(projectToPublish)'
    versioningScheme: 'off'
- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'tuyen-at-work - myget'