//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// Runtime Version:2.0.50727.42 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.IO;
using System.Threading.Tasks;

namespace TuyenPham.Base.Helpers
{
    public static class ProcessHelper
    {
        public static Task<int> RunAsync(
            string fileName,
            string command,
            string workingFolder)
        {
            var tcs = new TaskCompletionSource<int>();

            var currentDirectory = Directory.GetCurrentDirectory();

            Directory.CreateDirectory(workingFolder);
            Directory.SetCurrentDirectory(workingFolder);

            try
            {
                using var process = new Process
                {
                    StartInfo =
                    {
                        FileName = fileName,
                        Arguments = command,
                        WorkingDirectory = workingFolder
                    }
                };

                process.Exited += (sender, args) =>
                {
                    tcs.SetResult(process.ExitCode);
                    process.Dispose();
                };

                process.Start();
                return tcs.Task;
            }
            finally
            {
                Directory.SetCurrentDirectory(currentDirectory);
            }
        }
    }
}