//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// Runtime Version:2.0.50727.42 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using System.Diagnostics;
using System.IO;

namespace TuyenPham.CommonExtensions.Helpers
{
    internal static class ProcessHelper
    {
        internal static int RunAsync(
            string fileName,
            string command,
            string workingFolder)
        {
            var currentDirectory = Directory.GetCurrentDirectory();

            Directory.CreateDirectory(workingFolder);
            Directory.SetCurrentDirectory(workingFolder);

            try
            {
                using var cmd = new Process
                {
                    StartInfo =
                    {
                        FileName = fileName,
                        Arguments = command,
                        WorkingDirectory = workingFolder
                    }
                };
                cmd.Start();
                cmd.WaitForExit();

                Directory.SetCurrentDirectory(currentDirectory);

                return cmd.ExitCode;
            }
            catch
            {
                Directory.SetCurrentDirectory(currentDirectory);
                throw;
            }
            finally
            {
                Directory.SetCurrentDirectory(currentDirectory);
            }
        }
    }
}